name: py37
channels:
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37hc8dfbb8_1
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=openblas
  - bleach=3.1.0=py_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.10.14=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.11.8=py37h06a4308_0
  - cffi=1.13.2=py37h2e261b9_0
  - chardet=3.0.4=py37h06a4308_1003
  - cloudpickle=1.3.0=py_0
  - conda-pack=0.5.0=pyh9f0ad1d_0
  - cryptography=3.2.1=py37h3c74f83_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - cython=0.29.16=py37h3340039_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.13.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37_0
  - gast=0.3.3=py_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=243
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.16.0=py37_0
  - jinja2=2.11.1=py_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.0.0=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_core=4.6.1=py37_0
  - jupyter_nbextensions_configurator=0.4.1=py37_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_server=1.2.0=py_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - liblapack=3.8.0=11_openblas
  - libopenblas=0.3.6=h5a2b251_2
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.2.1=py_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2018.0.3=1
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.3.1=py37h06a4308_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37_0
  - numpy-base=1.17.4=py37h2f8d375_0
  - olefile=0.46=py_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1h=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.6.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - portalocker=1.5.2=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.4=py37he1b5a44_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycocotools=2.0.0=py37h516909a_1001
  - pycparser=2.19=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=20.0.0=pyhd3eb1b0_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.7=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyyaml=5.2=py37h516909a_0
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scikit-learn=0.23.1=py37h7ea95a0_0
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.2=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tbb=2020.0=hfd86e86_0
  - tbb4py=2020.0=py37hfd86e86_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_3
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - apex==0.1
    - asttokens==2.0.4
    - astunparse==1.6.3
    - attrdict==2.0.1
    - click==7.1.2
    - easydict==1.9
    - flask==1.1.2
    - flask-cors==3.0.9
    - geographiclib==1.50
    - geopy==1.22.0
    - grpcio==1.32.0
    - gunicorn==20.0.4
    - gym==0.17.2
    - idna==2.9
    - itsdangerous==1.1.0
    - jupyterthemes==0.20.0
    - lesscpy==0.14.0
    - marshmallow==3.8.0
    - mindinsight==1.0.0
    - mindspore==1.0.0
    - mindspore-gpu==1.0.0
    - mpmath==1.1.0
    - munch==2.5.0
    - mxnet-cu101==1.5.1
    - mxnet-cu101mkl==1.6.0
    - numpy==1.18.2
    - packaging==20.4
    - pandas==1.1.3
    - pillow==8.0.0
    - ply==3.11
    - pretrainedmodels==0.7.4
    - progress==1.5
    - psutil==5.7.2
    - pyglet==1.5.0
    - python-graphviz==0.8.4
    - pytz==2019.3
    - qgrid==1.3.0
    - requests==2.23.0
    - scipy==1.3.3
    - sympy==1.6.2
    - tabulate==0.8.7
    - tensorboard-logger==0.1.0
    - tensorboardx==2.1
    - thop==0.0.31-2005241907
    - timm==0.1.14
    - torch==1.4.0
    - torchsummaryx==1.3.0
    - torchvision==0.5.0
    - treelib==1.6.1
    - urllib3==1.25.8
    - yacs==0.1.7
    - yapf==0.30.0
prefix: /home/zhangys/anaconda3/envs/py37
